### ISSUE TITLE
Mesa history files dont handle retries, backups and restarts

### ISSUE THREAD

**Issue by rjfarmer** [warrickball/tomso#2]
https://github.com/warrickball/tomso/blob/018781b5221fa2f595a574c2706d9855faf05116/tomso/mesa.py#L38

Hi,
I noticed you history reading code is missing the ability to remove retries, backups and restarts (from photos) which usually messes up plots when the model number suddenly goes backwards for a bit :)

This chunk of code is adapted from my mesa reading code, its untested with yours but should be a good starting point:

    data=data[data['model_number']<=data['model_number'][-1]] # get all model numbers less than the last model    number (fixes issue if last model was from a restart and has a lower number than max(model_number)
    mod_rev=data['model_number'][::-1] # Reverse array of elements
    mod_uniq,mod_ind=np.unique(mod_rev,return_index=True) # This will return the index of the first unique model number, but as we reversed the array previously this is the last point in the array with this model number
    data=data[np.size(data['model_number'])-mod_ind-1] # Flip the reversed index back to "normal" index

**Comment by warrickball** [comment]
Sorry it took so long for me to see this! For no apparent reason, I don't think I set myself up to get notifications on these.

I've now incorporated the part that removes backpedalling because of retries and backups (https://github.com/warrickball/tomso/commit/89d96ea6ebcfe4912edfd7db58e07a2ddaecd054). I'm not sure what the first line you posted does but if you can send a history file (or an inlist for me to make one) that shows the problem, I can add it to the tests.

**Comment by rjfarmer** [comment]
The point of the first line is if you have done a restart from a photo and that it now ends earlier than the previous (pre-photo evolution). For instance say you had models 1 2 3 4 5 6, then restart at model 3 and that runs till model 5. So now the output is 1 2 3 4 5 6 3 4 5 .  You want to remove the first 5 and 6 as the model now ends on the second 5. By having just unique (like you do in 89d96ea) i think that 6 will still be in the output (as there is no later output with the same number but you want it gone as the model now ends before model 6). Hope that makes some sense

**Comment by warrickball** [comment]
Aha, I see what you mean. I've just added that line and generated some test data in commit https://github.com/warrickball/tomso/commit/5373496a61ed030afc0d5b55c36a36f535e592e9.
